language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
- gem install bundler -v 2.0.1
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  repo: rjt-gupta/rjt-gupta.github.io
  local-dir: ./site
  provider: pages
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master